In [1]:
%matplotlib inline

In [2]:
import numpy as np

In [3]:
cost_matrix = 1 - np.array(
        [
            [0.95, 0.76, 0.62, 0.41, 0.06],
            [0.23, 0.46, 0.79, 0.94, 0.35],
            [0.61, 0.02, 0.92, 0.92, 0.81],
            [0.49, 0.82, 0.74, 0.41, 0.01],
            [0.89, 0.44, 0.18, 0.89, 0.14],
        ]
    )

In [4]:
cost_matrix

array([[0.05, 0.24, 0.38, 0.59, 0.94],
       [0.77, 0.54, 0.21, 0.06, 0.65],
       [0.39, 0.98, 0.08, 0.08, 0.19],
       [0.51, 0.18, 0.26, 0.59, 0.99],
       [0.11, 0.56, 0.82, 0.11, 0.86]])

In [21]:
cost_matrix.min(axis=1)

array([0.05, 0.06, 0.08, 0.18, 0.11])

In [19]:
cost_matrix - cost_matrix.min()

array([[0.  , 0.19, 0.33, 0.54, 0.89],
       [0.72, 0.49, 0.16, 0.01, 0.6 ],
       [0.34, 0.93, 0.03, 0.03, 0.14],
       [0.46, 0.13, 0.21, 0.54, 0.94],
       [0.06, 0.51, 0.77, 0.06, 0.81]])

In [6]:
np.min?

Signature:
np.min(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the minimum of an array or minimum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the minimum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed

In [ ]:
def linear_assignment(cost_matrix):
    
    
    
linear_assignment(cost_matrix)